--- #YAML:1.0
name: CGI-Widget-Tabs
version: 1.08
license: perl
distribution_type: module
requires:
  Carp: 0
  HTML::Entities: 0
  Test::More: 0
  URI::Escape: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  CGI::Widget::Tabs:
    file: lib/CGI/Widget/Tabs.pm
    version: 1.08
  CGI::Widget::Tabs::Heading:
    file: lib/CGI/Widget/Tabs/Heading.pm
generated_by: Module::Build version 0.20
